version: "3.7"

services:
  FlyStudioEmail:
    container_name: EmailAPI
    image: flystudioemail:1.0.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.FlyStudioEmail.rule=Host(`email.flystudio.co.za`)"
      - "traefik.http.routers.FlyStudioEmail.entrypoints=websecure"
      - "traefik.http.routers.FlyStudioEmail.tls.certresolver=myresolver"
    build:
      context: ./
      dockerfile: ./email.dockerfile
    expose:
      - "7341"
    networks:
      - proxy

networks:
  proxy:
    external: true
