version: "3.7"

services:
  DarrenWebsite:
    container_name: DarrenWebsite
    image: darrenoosthuizen/darrenwebsite:2.0.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.DarrenWebsite.rule=Host(`darren.flystudio.co.za`)"
      - "traefik.http.routers.DarrenWebsite.entrypoints=websecure"
      - "traefik.http.routers.DarrenWebsite.tls.certresolver=myresolver"
    build:
      context: ./
      dockerfile: ./web.dockerfile
    expose:
      - "80"
    networks:
      - proxy
    volumes:
      - ./nginx/:/etc/nginx/

networks:
  proxy:
    external: true
